timeout: 15m
steps:
  - id: git-init
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - init
      - .
  - id: git-add
    name: gcr.io/cloud-builders/git
    args:
      - remote
      - add
      - -t
      - \*
      - -f
      - origin
      - https://github.com/Electroid/infrastructure.git
  - id: git-checkout
    name: gcr.io/cloud-builders/git
    args:
      - checkout
      - master
  - id: m2-download
    name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME/.m2
      - .
  - id: maven
    name: gcr.io/cloud-builders/mvn
    args:
      - install
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/workspace/.m2
  - id: m2-deploy
    name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - .m2
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME
  - id: docker-deploy
    name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - builds
      - submit
      - --async
      - --no-source
      - --substitutions=_BRANCH=$BRANCH_NAME,_VERSION=$_VERSION,_SPORTBUKKIT_VERSION=$_SPORTBUKKIT_VERSION,_BUNGEECORD_VERSION=$_BUNGEECORD_VERSION
      - --config=docker/minecraft/build.yml
